from .animals import Animal
from .donkey import Donkey
from .giraffe import Giraffe
from .llama import Llama
from .sloth import Sloth
from .tiger import Tiger
from .flower_horn_fish import FlowerHornFish
from .jellyfish import Jellyfish
from .puffer_fish import PufferFish
from .shark import Shark
from .stingray import Stingray
from .anaconda import Anaconda
from .boa_constrictor import BoaConstrictor
from .copperhead_snake import CopperheadSnake
from .python import Python
from .rat_snake import RatSnake
from .goose import Goose
